name: Nightly Test Suite

on:
  schedule:
    - cron: '0 23 * * *'  # Runs at 23:00 UTC (midnight Amsterdam time)
  workflow_dispatch:  # Allows manual triggering

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Install Playwright browsers
      run: npx playwright install --with-deps
    
    - name: Run regression tests
      run: npm run test:regression
      env:
        CI: true
    
    - name: Install Allure
      run: |
        curl -o allure-commandline-2.24.1.tgz -OL https://repo.maven.apache.org/maven2/io/qameta/allure/allure-commandline/2.24.1/allure-commandline-2.24.1.tgz
        tar -zxvf allure-commandline-2.24.1.tgz
        sudo ln -s $PWD/allure-2.24.1/bin/allure /usr/local/bin/allure
    
    - name: Generate Allure Report
      run: allure generate test-results --clean
    
    - name: Upload Allure Report
      uses: actions/upload-artifact@v4
      with:
        name: allure-report
        path: allure-report/
    
    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results
        path: |
          test-results/
          playwright-report/ 